### PR TITLE
Cleanup of Documentation info

### PR DESCRIPTION
**Pull request by patriziaazzi**
Cleanup of docs/file/links. 
I am trying to use also the cute "github-pages" but if I do not make the pull request it won't update.

### CODE REVIEW

**Comment by vvolkl** [comment]
Hi Patrizia,

I think github currently looks in the `gh-pages` branch to create the website. Maybe it is better to set the `master` branch as the source? Then you don't have to update both.

**Comment by patriziaazzi** [comment]
Dear Valentin,
thanks a lot for the suggestion... indeed!!!
This was my first try...
I have tried to go back to the gh-pages settings but I am not able to get there anymore... ooops.

Can you help?
Pat

Le 16 nov. 2020 à 11:59, vvolkl <notifications@github.com<mailto:notifications@github.com>> a écrit :



Hi Patrizia,

I think github currently looks in the gh-pages branch to create the website. Maybe it is better to set the master branch as the source? Then you don't have to update both.

**Comment by patriziaazzi** [comment]
Ok. Fixed the source in the master.

**Comment by patriziaazzi** [comment]
Valentin, can you please merge these changes? Apparently I cannot. Thanks

**Comment by vvolkl** [comment]
Patrizia, sure no problem. I also sent you again the invitation to join the github organization as owner.

**Comment by vvolkl** [comment]
The website https://hep-fcc.github.io/FCCeePhysicsPerformance/ is now created from the `master` branch, and I deleted the `gh-pages` branch to avoid confusion.

**Comment by patriziaazzi** [comment]
Thanks,
However this display is not the one with all my new modifications! :(

I am not a very expert GitHub user, and I am afraid i might have messed things up.
I cleaned up our documentation page so that the list of case studies is visible from the start (and this is in fact in the master).
However the "gh-pages" do not show that, but still the old one.

Can you help? Can you please explain where is my mistake? Maybe because I forked in the beginning instead of cloning?

Thanks a lot for the patience,
Pat



Le 16 nov. 2020 à 15:38, vvolkl <notifications@github.com<mailto:notifications@github.com>> a écrit :



The website https://hep-fcc.github.io/FCCeePhysicsPerformance/ is now created from the master branch, and I deleted the gh-pages branch to avoid confusion.

**Comment by vvolkl** [comment]
Hi Patrizia, sorry for the late reply. No problem - to  me it looks like you have some additional commits on your master branch now that didn't make it in this pull request. Since I squashed the commits here, I'll revert this and try to merge everything in #2

**Pull request merged**
