### PR TITLE
Updates to create HNL LLP samples

### PR DESCRIPTION
**Pull request by jalimena**
- make the instructions in the Readme a little clearer
- add the edm4hep_output_config.tcl file
- autoconvert madgraph models to python3
- change the lhe file name to reflect the default given mass point in the .dat file

FYI @rebecacern @suchitakulkarni

### CODE REVIEW

**Comment by EmanuelPerez** [comment]
Hi Juliette, thanks for contributing ! I suggest that you adapt the instructions in order to pick up the configuration cards that are being used for the central MC production - such that your signal samples and the common background samples will correspond to the same thing. See here, https://github.com/HEP-FCC/FCCeePhysicsPerformance/tree/master/General#common-event-samples. The cards (both the Delphes card, and the corresponding edm4hep_output_config.tcl) can be found in the FCC-config repository, currently in the "spring2021" branch.

**Comment by rebecacern** [comment]
Hi Emanuel, 
Right now there are no HNL in the central production (am I right?). 
However, we would want to centrally produce samples towards a snowmass paper, do you think that could be possible? We could start by this as a test maybe. In that case however it would be good to eventually involve other people as well, since parallel work is happening e.g. at UniGe.

**Comment by jalimena** [comment]
@EmanuelPerez ,
Ok, I have adapted the instructions (and tested that it works), see my new commit. Let me know if there's a more intelligent way to do it.

@EmanuelPerez  and @rebecacern , 
If we want to then have these samples eventually be centrally produced, should I then submit a new PR to put the configs in the FCC-config repository? If so, where do I put the madgraph dat card - there seems to be no place for that? And probably we will want several masses, lifetimes, decay modes - would separate configs all go in there? Or maybe we should do more private tests first before we ask for centrally produced samples..

**Comment by EmanuelPerez** [comment]
Thanks Juliette, PR is merged.
Re: the production: Yes, please go first with private tests !

**Pull request merged**
