### PR TITLE
Zh recoil

### PR DESCRIPTION
**Pull request by AngLICERN**
Hi,

I added the APCHiggsTools with new Z builders. Configuration files used in APC were also added.
doPlots.py now can handle multiple signals. Fitting program fit_dev.py and its configuration file fit.py were added.

The fitting program now uses the RooCrystalBall, which is new in ROOT 6.24/00 used in the latest FCC software stack. One doesn't need to link other library for the DSCB.

Ang LI

### CODE REVIEW

**Comment by EmanuelPerez** [comment]
Thanks  a lot for this Ang ! I see that you have a method get_MET_cosTheta, where MET sounds like missing ET. But that's actually the cosTheta of the whole missing momentum. Could you please rename it, into e.g. get_cosTheta_miss ?

**Comment by AngLICERN** [comment]
Thank you for pointing out, the function was renamed.

**Comment by EmanuelPerez** [comment]
Thanks a lot Ang !  The PR is merged now.

**Comment by clementhelsens** [comment]
hello!
as discussed by email, I do not see a reason why the doPlots.py should not be in the main HEP-FCC/FCCAnalyses

**Comment by AngLICERN** [comment]
> Thanks a lot Ang ! The PR is merged now.

I will also try to add README for the new analysis tools this week.

**Comment by AngLICERN** [comment]
> hello!
> as discussed by email, I do not see a reason why the doPlots.py should not be in the main HEP-FCC/FCCAnalyses

Hello Clement,
I will do it later today or early tomorrow.

**Pull request merged**
