### PR TITLE
New skim for FCCAnalyses configuration in FCCeePhysicsPerformance

### PR DESCRIPTION
**Pull request by clementhelsens**
This is a first step, more will come for general documentation etc...
I think we could already merge this one and I will make an other one later

### CODE REVIEW

**Comment by EmanuelPerez** [comment]
Hi Clement, thanks for this. I think, though, that what you propose in the case-studies/README.md is too extreme: "it is requested to store and maintain the **four** FCCAnalyses python configuration files". While I agree that people should have an analysis.py and a preSel.py that use the common code in order to produce the ntuples, I do not think that we should force people to use the plotting script (even though it nicely does the normalisation properly for the user).

**Comment by clementhelsens** [comment]
Ok , what about: highly encouraged?

Le 3 déc. 2020 à 12:15, EmanuelPerez <notifications@github.com<mailto:notifications@github.com>> a écrit :


Hi Clement, thanks for this. I think, though, that what you propose in the case-studies/README.md is too extreme: "it is requested to store and maintain the four FCCAnalyses python configuration files". While I agree that people should have an analysis.py and a preSel.py that use the common code in order to produce the ntuples, I do not think that we should force people to use the plotting script (even though it nicely does the normalisation properly for the user).

**Comment by clementhelsens** [comment]
On the other hand, I believe it is important to ensure a uniform style for the plots, it's much easier to understand from a common style that results come from the same study, so I'd push for it when possible.

**Comment by EmanuelPerez** [comment]
"highly encouraged" for the plotting script sounds much better, thanks.
"a uniform common style" : yes agreed, but this could be ensured with a simple common style macro (a la .rootlogon.C for example). My concern about the generic plotting script is that the doPlots.py may not be generic enough to accommodate all use cases (and trying to make it generic enough may not be really worth it).

**Comment by clementhelsens** [comment]
@EmanuelPerez , I have modified the README.

**Pull request merged**
