### PR TITLE
Add ZH leptonic recoil fit

### PR DESCRIPTION
**Pull request by clementhelsens**

### CODE REVIEW

**Comment by EmanuelPerez** [comment]
Hi Clement, thanks, that's useful. I think one should not show the numerical results of the fit, though, since the errors on the fitted parameters will be very different once the energy spread is accounted for. And for the second plot, can you please specify which channel it corresponds to (for people who would try to reproduce it). Thanks.

**Comment by clementhelsens** [comment]
@EmanuelPerez , I have slightly modified the README to account for your comments. I still believe, as an example, it is important to display the fit result, so that people can cross check (the explicitly command is written to that extend)

**Comment by EmanuelPerez** [comment]
OK, now that the channel used for the fit is indicated, the reproducibility can be an argument for showing it. I did not want people to attach too much importance to the numerical result (BES will have a big effect for the mumu result), but now it is made clear that this is shown for technical purposes. I'll merge it now,

**Comment by clementhelsens** [comment]
@EmanuelPerez , 
I have added this example under the case-studies, but  after given it some more thoughts,  I believe, as we discussed with @gganis, that we are duplicating the work. 

I think we should have the code only in one place, for example changing:
https://github.com/HEP-FCC/FCCAnalyses/tree/master/FCCeeAnalyses/ZH_Zmumu

to 

https://github.com/HEP-FCC/FCCAnalyses/tree/master/FCCeeAnalyses/Higgs/mH-recoil/XX(XX=ee,mumu,qq)

and

https://github.com/HEP-FCC/FCCAnalyses/tree/master/FCCeeAnalyses/Higgs/mH-recoil/utils/

where we have for example the fitting code I used.

Also this will allow to have the same structure than FCCeePhyicsPerformance in FCCAnalyses.
Additionally we could add in each analyses in FCCAnalyses, a short README with people who have really contributed to develop the code, or that are simply running it. This is important that proper credit is given to the right persons, and not just the one that was able to blindly run few commands.

So I believe we should revert this PR and I will reorganise FCCAnalyses to reflect the above.

**Pull request merged**
